/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\public\provod.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Provod(props) {
  const { nodes, materials } = useGLTF("/provod.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.04, -0.06, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder044.geometry}
          material={materials.Material__26}
          scale={0.01}>
        </mesh>
      </group>
      <group
        position={[0.04, 1.06, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder045.geometry}
          material={materials.Material__26}
          scale={0.01}>
        </mesh>
      </group>
      <group
        position={[0.04, 1.3, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder046.geometry}
          material={materials.Material__26}
          scale={0.01}>
        </mesh>
      </group>
      <group
        position={[0.04, 1.43, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder047.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.04, 2.46, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder048.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.09, 1.25, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder049.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.09, 2.27, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.08, 1.25, -0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder051.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.08, 2.27, -0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder052.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.03, 1.25, -0.12]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder053.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.03, 2.27, -0.12]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder054.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.01, 1.25, -0.1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder055.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0, 2.27, -0.1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder056.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.01, 1.25, -0.06]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder057.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.01, 2.27, -0.06]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder058.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.02, 1.25, -0.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder059.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.02, 2.27, -0.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder060.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.06, 1.25, -0.04]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder061.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.06, 2.27, -0.04]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder062.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.15, 1, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder063.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.15, 2.02, -0.08]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder064.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.13, 1, -0.14]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder065.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.14, 2.02, -0.14]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder066.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.1, 1, -0.18]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder067.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.1, 2.02, -0.18]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder068.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.03, 1, -0.2]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder069.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.03, 2.02, -0.2]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder070.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.02, 1, -0.18]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder071.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.02, 2.02, -0.18]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder072.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.06, 1, -0.15]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder073.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.06, 2.02, -0.15]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder074.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.07, 1, -0.1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder075.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.07, 2.02, -0.1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder076.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.07, 1, -0.04]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder077.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.07, 2.02, -0.04]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder078.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.04, 1, 0.01]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder079.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[-0.04, 2.02, 0.01]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder080.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.03, 1, 0.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder081.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.03, 2.02, 0.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder082.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.09, 1, 0.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder083.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.09, 2.02, 0.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder084.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.13, 1, -0.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder085.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
      <group
        position={[0.13, 2.02, -0.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.97, 0.98, 1.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder086.geometry}
          material={materials["fallback Material"]}
          scale={0.01}>
          <meshStandardMaterial color={"#778288"} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/provod.glb");
