/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Provod(props) {
  const { nodes, materials } = useGLTF("/provod.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.black.geometry}
        material={materials["Material #25"]}
        position={[0.03566185, -0.05697933, -0.07602501]}
        scale={[0.00972693, 0.0140681, 0.00975168]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder045.geometry}
        material={materials["Material #26"]}
        position={[0.03527267, 1.06445003, -0.07792457]}
        scale={[0.00972693, 0.0140681, 0.00975168]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.white.geometry}
        material={materials["Material #29"]}
        position={[-0.0099221, 1.24896562, -0.05660156]}
        scale={[0.00972693, 0.0140681, 0.00975168]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.red.geometry}
        material={materials["Material.001"]}
        position={[0.09552315, 0.99949574, -0.18190971]}
        scale={[0.00972693, 0.0140681, 0.00975168]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.blue.geometry}
        material={materials["Material.002"]}
        position={[-0.01977631, 0.99949574, -0.18475525]}
        scale={[0.00972693, 0.0140681, 0.00975168]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cuprum.geometry}
        material={materials["Material #27"]}
        position={[-0.0361657, 2.02245522, 0.00638985]}
        scale={[0.00972693, 0.0140681, 0.00975168]}
      />
    </group>
  );
}

useGLTF.preload("/provod.glb");
