/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Wire(props) {
  const { nodes, materials } = useGLTF("/wire.glb");
  return (
    <group {...props} dispose={null} scale={2}>
      <group
        position={[0.39, 0.084, -0.005]}
        rotation={[-Math.PI / 2, -0.425, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.003"]}
          scale={0.01}
        />
      </group>
      <group
        position={[0.209, 0.487, -0.005]}
        rotation={[-Math.PI / 2, -0.425, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials.Material__26}
          scale={0.01}
        />
      </group>
      <group
        position={[0.207, 0.493, -0.005]}
        rotation={[-Math.PI / 2, -0.425, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.004"]}
          scale={0.01}
        />
      </group>
      <group
        position={[0.156, 0.607, -0.004]}
        rotation={[-Math.PI / 2, -0.425, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials["fallback Material.001"]}
          scale={0.01}
        />
      </group>
      <group
        position={[0.149, 0.623, -0.004]}
        rotation={[-Math.PI / 2, -0.425, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials.Material__29}
          scale={0.01}
        />
      </group>
      <group
        position={[0.135, 0.653, -0.004]}
        rotation={[-Math.PI / 2, -0.425, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.Material__30}
          scale={0.01}
        />
      </group>
      <group
        position={[-0.083, 1.057, -0.019]}
        rotation={[-Math.PI / 2, -0.425, 0]}
        scale={[0.997, 0.997, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder072.geometry}
          material={materials["Material.002"]}
          scale={0.01}
        />
      </group>
      <group
        position={[0.03, 0.872, -0.037]}
        rotation={[-Math.PI / 2, -0.425, 0]}
        scale={[0.997, 0.997, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder067.geometry}
          material={materials["Material.001"]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/wire.glb");
